pragma Singleton

import QtQuick

// AUTO-GENERATED by setup.sh from DOTFILES_APP_WHITELIST in setup.conf —
// do not hand-edit this file; changes here are overwritten on the next
// run. To add/remove an allowed app, edit setup.conf (or, for a personal
// override that isn't committed, setup.conf.local) instead, then re-run
// setup.sh. Or just check what's currently configured with:
//   ./setup.sh --list-whitelist
//
// Find the exact desktop-entry ID for an app with:
//   find /usr/share/applications ~/.local/share/applications -name '*.desktop'
QtObject {
  readonly property list<string> allowedAppIds: [
    "discord.desktop",
    "com.vysp3r.ProtonPlus.desktop",
    "librewolf.desktop",
    "nm-connection-editor.desktop",
    "scrcpy.desktop",
    "steam.desktop",
    "r2modman.desktop",
    "localsend.desktop"
  ]
}
