#!/usr/bin/env bash
# =============================================================================
# lib/wallpaperconf.sh — generates
# ~/.config/quickshell/wallpaper/monitors.conf from DOTFILES_WALLPAPER_DIRS
# in setup.conf.
#
# Unlike the app whitelist, this is written directly into $HOME (a real
# file, never symlinked/tracked in the repo) rather than regenerated inside
# the repo's own source tree: it necessarily embeds this specific machine's
# absolute home directory path, and the repo tree is shared/portable
# source that must stay identical across machines. Writing straight to
# $HOME keeps machine-specific data out of git entirely, consistent with
# how DOTFILES_ENSURE_DIRS already treats personal data as real files, not
# tracked/symlinked content.
#
# Depends on: lib/log.sh, lib/backup.sh
# =============================================================================

# wallpaperconf::render <output_conf_file> <home_dir>
#
# No-op if the generated content already matches what's on disk.
wallpaperconf::render() {
  local dst="$1" home_dir="$2" entry monitor rel content

  content="# AUTO-GENERATED by setup.sh from DOTFILES_WALLPAPER_DIRS in setup.conf —
# do not hand-edit; changes here are overwritten on the next run.
# Format: MONITOR_NAME=/absolute/path, one per line.
"

  for entry in "${DOTFILES_WALLPAPER_DIRS[@]}"; do
    [[ -z "$entry" ]] && continue
    monitor="${entry%%:*}"
    rel="${entry#*:}"
    if [[ -z "$monitor" || -z "$rel" || "$monitor" == "$entry" ]]; then
      log::warn "Ignoring malformed DOTFILES_WALLPAPER_DIRS entry (expected MONITOR:path): $entry"
      continue
    fi
    content+="$monitor=$home_dir/$rel"$'\n'
  done

  if [[ -f "$dst" ]] && [[ "$(cat -- "$dst" 2>/dev/null)" == "$content" ]]; then
    log::debug "Per-monitor wallpaper config already up to date: $dst"
    return 0
  fi

  log::info "Regenerating per-monitor wallpaper config ($dst): ${#DOTFILES_WALLPAPER_DIRS[@]} entr$([[ ${#DOTFILES_WALLPAPER_DIRS[@]} -eq 1 ]] && echo y || echo ies)"
  if [[ "${DOTFILES_DRY_RUN:-false}" == "true" ]]; then
    log::info "[dry-run] would write: ${DOTFILES_WALLPAPER_DIRS[*]:-<none>}"
    return 0
  fi

  if [[ -e "$dst" || -L "$dst" ]]; then
    backup::file "$dst" "$dst" || { log::error "Could not back up existing $dst; leaving it untouched."; return 1; }
  fi

  mkdir -p -- "$(dirname -- "$dst")"
  printf '%s' "$content" > "$dst"
}
