#!/usr/bin/env bash
# =============================================================================
# lib/whitelist.sh — generates common/Whitelist.qml from the single,
# editable source of truth: DOTFILES_APP_WHITELIST in setup.conf (or
# setup.conf.local).
#
# This exists because the app launcher's allow-list used to be hardcoded
# QML with no link to any config file at all — exactly the kind of
# "customize before running" setting setup.conf is supposed to hold.
# setup.conf is now authoritative; the .qml file is a generated artifact
# kept in sync with it (regenerated in the repo's own source tree, so the
# existing generic file-linker in lib/link.sh picks it up like any other
# tracked file — no special-casing needed there).
#
# Depends on: lib/log.sh
# =============================================================================

# whitelist::render <output_qml_file>
#
# Regenerates the QML file from DOTFILES_APP_WHITELIST. No-op if the
# generated content already matches what's on disk, so re-running
# setup.sh without any config changes never dirties the working tree.
whitelist::render() {
  local dst="$1" app content joined
  local -a lines=()

  for app in "${DOTFILES_APP_WHITELIST[@]}"; do
    lines+=("    \"$app\"")
  done

  if (( ${#lines[@]} > 0 )); then
    joined="$(printf '%s,\n' "${lines[@]}")"
    # Command substitution above already strips ALL trailing newlines, so
    # the trailing separator left to remove is just the final comma (not
    # "comma+newline" — that pattern can never match here and silently
    # leaves a dangling trailing comma before the closing `]`).
    joined="${joined%,}"
  else
    joined=""
  fi

  content="pragma Singleton

import QtQuick

// AUTO-GENERATED by setup.sh from DOTFILES_APP_WHITELIST in setup.conf —
// do not hand-edit this file; changes here are overwritten on the next
// run. To add/remove an allowed app, edit setup.conf (or, for a personal
// override that isn't committed, setup.conf.local) instead, then re-run
// setup.sh. Or just check what's currently configured with:
//   ./setup.sh --list-whitelist
//
// Find the exact desktop-entry ID for an app with:
//   find /usr/share/applications ~/.local/share/applications -name '*.desktop'
QtObject {
  readonly property list<string> allowedAppIds: [
$joined
  ]
}
"

  if [[ -f "$dst" ]] && [[ "$(cat -- "$dst" 2>/dev/null)" == "$content" ]]; then
    log::debug "App whitelist already up to date: $dst"
    return 0
  fi

  log::info "Regenerating app whitelist ($dst): ${#DOTFILES_APP_WHITELIST[@]} app(s)"
  if [[ "${DOTFILES_DRY_RUN:-false}" == "true" ]]; then
    log::info "[dry-run] would write: ${DOTFILES_APP_WHITELIST[*]:-<none>}"
    return 0
  fi

  mkdir -p -- "$(dirname -- "$dst")"
  printf '%s' "$content" > "$dst"
}

# whitelist::print — one app ID per line, straight from the resolved
# config (setup.conf + setup.conf.local). Used by --list-whitelist and the
# interactive menu's "View whitelisted apps" entry — both call this same
# function, so there's exactly one implementation of "what's whitelisted".
whitelist::print() {
  local app
  if (( ${#DOTFILES_APP_WHITELIST[@]} == 0 )); then
    echo "(none configured)"
    return 0
  fi
  for app in "${DOTFILES_APP_WHITELIST[@]}"; do
    printf '%s\n' "$app"
  done
}
