pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io

Singleton {
  id: root

  // --- Shared library state -----------------------------------------------
  property list<string> wallpapers: []
  property string backend: "awww"

  // --- Per-monitor state ---------------------------------------------------
  // monitor name -> currently-applied wallpaper path. "__default__" holds
  // the legacy pre-multi-monitor global selection (or the last "All
  // Monitors" apply), used as the fallback for any monitor without its
  // own explicit entry.
  property var currentWallpapers: ({})

  // monitor name -> absolute source directory, from
  // ~/.config/quickshell/wallpaper/monitors.conf (generated by setup.sh
  // from DOTFILES_WALLPAPER_DIRS in setup.conf). Monitors not present here
  // just use the shared library.
  property var perMonitorDirs: ({})

  // monitor name -> wallpapers found in that monitor's own directory.
  property var perMonitorWallpapers: ({})

  property var _scanQueue: []

  // Scan the shared wallpaper directories.
  //
  // NOTE: this path is duplicated (not templated/generated) from
  // DOTFILES_ENSURE_DIRS's "Pictures/Wallpapers" entry in setup.conf — the
  // two must be kept in sync by hand. They're intentionally not wired
  // together like the app whitelist is: DOTFILES_ENSURE_DIRS only ever
  // controls "keep this a real directory instead of a symlink", it has no
  // general mechanism for injecting a path into an arbitrary shell command
  // embedded in QML. If you rename/move the wallpaper directory, update
  // both this `find` command and setup.conf.
  Process {
    id: scanner
    command: ["sh", "-c",
      "find ~/Pictures/Wallpapers ~/Pictures -maxdepth 2 -type f \\( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \\) 2>/dev/null | sort -u | head -200"
    ]
    running: false
    stdout: SplitParser {
      onRead: data => {
        const path = data.trim();
        if (path !== "") {
          root.wallpapers = [...root.wallpapers, path];
        }
      }
    }
  }

  // --- Per-monitor directory config (~/.config/quickshell/wallpaper/monitors.conf) ---
  FileView {
    id: monitorsConfigFile
    path: Quickshell.env("HOME") + "/.config/quickshell/wallpaper/monitors.conf"
    onTextChanged: root._parseMonitorDirs(monitorsConfigFile.text())
  }

  function _parseMonitorDirs(text) {
    const dirs = {};
    const lines = (text || "").split("\n");
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed === "" || trimmed.startsWith("#")) continue;
      const eq = trimmed.indexOf("=");
      if (eq <= 0) continue;
      const monitor = trimmed.slice(0, eq).trim();
      const dir = trimmed.slice(eq + 1).trim();
      if (monitor !== "" && dir !== "") dirs[monitor] = dir;
    }
    root.perMonitorDirs = dirs;
    root.perMonitorWallpapers = {};
    root._scanQueue = Object.keys(dirs);
    root._scanNextInQueue();
  }

  function _scanNextInQueue() {
    if (root._scanQueue.length === 0) return;
    const monitor = root._scanQueue[0];
    const dir = root.perMonitorDirs[monitor];
    monitorScanner.monitor = monitor;
    monitorScanner.command = ["sh", "-c",
      "find \"$1\" -maxdepth 2 -type f \\( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \\) 2>/dev/null | sort -u | head -200",
      "sh", dir];
    monitorScanner.running = true;
  }

  // Reused sequentially for every configured monitor directory — simpler
  // and safer than spinning up one dynamic Process per monitor.
  Process {
    id: monitorScanner
    property string monitor: ""
    running: false
    stdout: SplitParser {
      onRead: data => {
        const path = data.trim();
        if (path === "") return;
        const existing = root.perMonitorWallpapers[monitorScanner.monitor] || [];
        const updated = Object.assign({}, root.perMonitorWallpapers);
        updated[monitorScanner.monitor] = [...existing, path];
        root.perMonitorWallpapers = updated;
      }
    }
    onRunningChanged: {
      if (!running && root._scanQueue.length > 0) {
        root._scanQueue = root._scanQueue.slice(1);
        root._scanNextInQueue();
      }
    }
  }

  // --- Persisted per-monitor selection (~/.config/quickshell/wallpaper/wallpaper.conf) ---
  FileView {
    id: stateFile
    path: Quickshell.env("HOME") + "/.config/quickshell/wallpaper/wallpaper.conf"
    onTextChanged: root._parseState(stateFile.text())
  }

  function _parseState(text) {
    const state = {};
    const lines = (text || "").split("\n");
    for (const line of lines) {
      const trimmed = line.trim();
      if (trimmed === "") continue;
      const eq = trimmed.indexOf("=");
      if (eq > 0) {
        state[trimmed.slice(0, eq).trim()] = trimmed.slice(eq + 1).trim();
      } else {
        // Legacy format: a single bare path from before per-monitor
        // support existed. Kept as the fallback default so upgrading
        // never silently loses the user's existing wallpaper choice.
        state["__default__"] = trimmed;
      }
    }
    root.currentWallpapers = state;
  }

  Component.onCompleted: {
    scanner.running = true;
  }

  function rescan() {
    wallpapers = [];
    scanner.running = true;
    root.perMonitorWallpapers = {};
    root._scanQueue = Object.keys(root.perMonitorDirs);
    root._scanNextInQueue();
  }

  // wallpapersFor(monitorName) — "" means the shared library (used by the
  // "All Monitors" tab); a specific monitor with its own configured,
  // non-empty directory sees only that directory, otherwise it also falls
  // back to the shared library.
  function wallpapersFor(monitorName) {
    if (!monitorName) return root.wallpapers;
    const own = root.perMonitorWallpapers[monitorName];
    if (own && own.length > 0) return own;
    return root.wallpapers;
  }

  // currentFor(monitorName) — what's actually showing on a given monitor,
  // honoring its own state first and falling back to the legacy/global
  // default so the "active" indicator stays accurate right after
  // upgrading from the old single-wallpaper format.
  function currentFor(monitorName) {
    if (monitorName && root.currentWallpapers[monitorName]) return root.currentWallpapers[monitorName];
    return root.currentWallpapers["__default__"] || "";
  }

  // setWallpaper(path, monitorName) — monitorName === "" applies to every
  // currently connected monitor at once; a specific monitor name applies
  // to just that output via awww/swww's --outputs flag.
  function setWallpaper(path, monitorName) {
    if (!monitorName) {
      const targets = Quickshell.screens.map(s => s.name).filter(n => !!n);
      if (targets.length === 0) {
        _applyTo(path, "");
      } else {
        for (const name of targets) _applyTo(path, name);
      }
      return;
    }
    _applyTo(path, monitorName);
  }

  function _applyTo(path, monitorName) {
    const updated = Object.assign({}, root.currentWallpapers);
    updated[monitorName || "__default__"] = path;
    root.currentWallpapers = updated;

    const cmd = ["awww", "img", path,
      "--transition-type", "grow", "--transition-pos", "center",
      "--transition-duration", "1"];
    if (monitorName) cmd.push("--outputs", monitorName);
    setProcess.command = cmd;
    setProcess.running = true;

    _saveState();
  }

  function _saveState() {
    let lines = [];
    for (const key in root.currentWallpapers) {
      lines.push(key + "=" + root.currentWallpapers[key]);
    }
    saveProcess.command = ["sh", "-c",
      'mkdir -p "$(dirname "$1")" && printf "%s" "$2" > "$1"',
      "sh",
      Quickshell.env("HOME") + "/.config/quickshell/wallpaper/wallpaper.conf",
      lines.join("\n") + "\n"];
    saveProcess.running = true;
  }

  Process {
    id: setProcess
    command: []
    running: false
  }

  Process {
    id: saveProcess
    command: []
    running: false
  }
}

